<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load('/etc/ahcis/db/')
%>

<%= bcdb.shib_encryption_datasource :database, 'shib_encryption_datasource' %>
<%= bcdb.development :database, 'development' %>
<%= bcdb.test :database, 'test' %>
<%= bcdb.production :database, 'production' %>